title: Josh Beard
description: "I‚Äôm a marketing professional who builds long-term value for organizations."
color_theme: auto
remote_theme: sylhare/Type-on-Strap
header_text: Welcome to my blog
footer_text: ü§ç
paginate: 5
excerpt: true
